webserver:
  bind_address: :8080
  bind_dashboard_address: :8082
  ssl: false
  ssl_cert_file: ""
  ssl_key_file: ""
ai:
  command: python
  detectPath: /home/gangqiangsun/MYPROJECT/PYTHON/yolov5/detect.py
  inputPath: /home/gangqiangsun/MYPROJECT/PYTHON/yolov5/input
  outPath: /home/gangqiangsun/MYPROJECT/PYTHON/yolov5/out
